services:
  go-api1:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: 512M
    ports:
      - "8081:8081"

  go-api2:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: 512M
    ports:
      - "8082:8081"
