services:
  typescript-api:
    build:
      context: ./typescript
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 128M
    ports:
      - "8080:8080"

  go-api1:
    build:
      context: ./go
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 128M
    ports:
      - "8081:8081"

  go-api2:
    build:
      context: ./go
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 128M
    ports:
      - "8082:8081"
